"""Add assigned_closer to LeadProfile

Revision ID: 2c15513ca8c1
Revises: c6f2b1177c81
Create Date: 2026-01-15 18:19:07.759171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c15513ca8c1'
down_revision = 'c6f2b1177c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_closer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_closer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_closer_id')

    # ### end Alembic commands ###
