"""add google calendar tokens

Revision ID: 823187cb13ca
Revises: 9d052dfcdf2f
Create Date: 2026-01-19 10:39:53.920418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823187cb13ca'
down_revision = '9d052dfcdf2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_calendar_tokens')
    # ### end Alembic commands ###
