"""Add google_calendar_id preference

Revision ID: 945674423935
Revises: ebc645133c76
Create Date: 2026-01-19 13:11:03.340663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945674423935'
down_revision = 'ebc645133c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_calendar_tokens', schema=None) as batch_op:
        batch_op.drop_column('google_calendar_id')

    # ### end Alembic commands ###
