"""refactor_daily_report_dynamic

Revision ID: 9d052dfcdf2f
Revises: 68520c08d44f
Create Date: 2026-01-17 19:38:57.752034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d052dfcdf2f'
down_revision = '68520c08d44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_report_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_stats_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['daily_stats_id'], ['closer_daily_stats.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['daily_report_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calls_scheduled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calls_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calls_no_show', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('calls_canceled', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cash_collected', sa.Float(), nullable=True))
        batch_op.drop_column('slots_available')
        batch_op.drop_column('improvement_area')
        batch_op.drop_column('first_agendas_canceled')
        batch_op.drop_column('second_agendas')
        batch_op.drop_column('presentations')
        batch_op.drop_column('followups_started_booking')
        batch_op.drop_column('sales_on_call')
        batch_op.drop_column('second_agendas_attended')
        batch_op.drop_column('objection_form_completed')
        batch_op.drop_column('first_agendas_rescheduled')
        batch_op.drop_column('second_calls_booked')
        batch_op.drop_column('first_agendas_no_show')
        batch_op.drop_column('replies_sales')
        batch_op.drop_column('second_agendas_rescheduled')
        batch_op.drop_column('first_agendas')
        batch_op.drop_column('notion_completed')
        batch_op.drop_column('second_agendas_no_show')
        batch_op.drop_column('sales_followup')
        batch_op.drop_column('first_agendas_attended')
        batch_op.drop_column('win_of_day')
        batch_op.drop_column('replies_booking')
        batch_op.drop_column('second_agendas_canceled')
        batch_op.drop_column('followups_started_closing')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closer_daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followups_started_closing', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_agendas_canceled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('replies_booking', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('win_of_day', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('first_agendas_attended', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sales_followup', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_agendas_no_show', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('notion_completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('first_agendas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_agendas_rescheduled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('replies_sales', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_agendas_no_show', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_calls_booked', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_agendas_rescheduled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('objection_form_completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('second_agendas_attended', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sales_on_call', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('followups_started_booking', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('presentations', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('second_agendas', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('first_agendas_canceled', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('improvement_area', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('slots_available', sa.INTEGER(), nullable=True))
        batch_op.drop_column('cash_collected')
        batch_op.drop_column('sales_amount')
        batch_op.drop_column('sales_count')
        batch_op.drop_column('calls_canceled')
        batch_op.drop_column('calls_no_show')
        batch_op.drop_column('calls_completed')
        batch_op.drop_column('calls_scheduled')

    op.drop_table('daily_report_answers')
    op.drop_table('daily_report_questions')
    # ### end Alembic commands ###
