"""Add integrations table

Revision ID: bf217e9343c3
Revises: 2c15513ca8c1
Create Date: 2026-01-15 18:36:39.814198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf217e9343c3'
down_revision = '2c15513ca8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url_dev', sa.String(length=255), nullable=True),
    sa.Column('url_prod', sa.String(length=255), nullable=True),
    sa.Column('active_env', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('integrations')
    # ### end Alembic commands ###
