"""add_closer_daily_stats

Revision ID: dbaf990ed21c
Revises: bf217e9343c3
Create Date: 2026-01-15 22:34:02.684079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaf990ed21c'
down_revision = 'bf217e9343c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['assigned_closer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
